In [7]:
import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.compose import ColumnTransformer

In [8]:
lr = LinearRegression()


ames = pd.read_csv("AmesHousing.csv")
X = ames[["Gr Liv Area", "TotRms AbvGrd"]]
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train_s = (X_train - X_train.mean())/X_train.std()

lr_fitted = lr.fit(X_train_s, y_train)
lr_fitted.coef_

array([ 70935.17656886, -16825.68984943])

In [9]:
X_test_s = (X_test - X_train.mean())/X_train.std()
y_preds = lr_fitted.predict(X_test_s)

r2_score(y_test, y_preds)

0.5130046146484101

In [10]:
new_house = pd.DataFrame(data = {"Gr Liv Area": [889], "TotRms AbvGrd": [6]})
new_house

   Gr Liv Area  TotRms AbvGrd
0          889              6

In [11]:
new_house_s = (new_house - X_train.mean())/X_train.std()
lr_fitted.predict(new_house_s)

array([102116.81994397])

Creating a Pipeline Objects

In [12]:
lr = LinearRegression()

lr_pipeline = Pipeline(
  [StandardScaler(),lr]
)

lr_pipeline

TypeError: 'LinearRegression' object is not subscriptable

In [13]:
lr_pipeline = Pipeline(
  [("standardize", StandardScaler()),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('standardize', StandardScaler()),
                ('linear_regression', LinearRegression())])

In [14]:
lr_pipeline_fitted = lr_pipeline.fit(X_train, y_train)

y_preds = lr_pipeline_fitted.predict(X_test)
r2_score(y_test, y_preds)

0.5130046146484101

In [15]:
lr_pipeline_fitted.predict(new_house)

array([102116.81994397])

In [16]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
)


lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
)

lr_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('dummify',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Bldg Type']),
                                                 ('standardize',
                                                  StandardScaler(),
                                                  ['Gr Liv Area',
                                                   'TotRms AbvGrd'])])),
                ('linear_regression', LinearRegression())])

In [17]:
X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]



X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_fitted = lr_pipeline.fit(X_train, y_train)

In [18]:
ct_fitted = ct.fit(X_train)

ct.transform(X_train)

array([[ 1.        ,  0.        ,  0.        , ...,  0.        , -1.13046514,
        -1.56704142],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.56639801,
         0.35415836],
       [ 0.        ,  0.        ,  0.        , ...,  1.        , -0.61676114,
        -0.92664149],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.24810298,
        -0.28624157],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.61008488,
         0.35415836],
       [ 1.        ,  0.        ,  0.        , ...,  0.        ,  0.98478662,
         1.6349582 ]])

In [19]:
ct.transform(X_test)

array([[ 1.        ,  0.        ,  0.        , ...,  0.        , -0.90080924,
        -0.28624157],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.01643255,
         0.99455828],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.90080924,
        -0.28624157],
       ...,
       [ 0.        ,  1.        ,  0.        , ...,  0.        , -0.81015559,
        -0.28624157],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -0.30853874,
        -0.28624157],
       [ 1.        ,  0.        ,  0.        , ...,  0.        , -1.0639858 ,
        -0.92664149]])

In [20]:
lr_pipeline_fitted.named_steps['linear_regression'].coef_

array([ 70919.03108633, -16821.86017148])

In [21]:
lr_pipeline = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
).set_output(transform="pandas")


ct.fit_transform(X_train)

      dummify__Bldg Type_1Fam  ...  standardize__TotRms AbvGrd
156                       1.0  ...                   -1.567041
2560                      1.0  ...                    0.354158
299                       0.0  ...                   -0.926641
961                       1.0  ...                    0.354158
1518                      1.0  ...                    0.354158
...                       ...  ...                         ...
1886                      1.0  ...                   -0.926641
1921                      1.0  ...                   -0.286242
1534                      1.0  ...                   -0.286242
2899                      1.0  ...                    0.354158
1090                      1.0  ...                    1.634958

[2197 rows x 7 columns]

In [22]:
ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
).set_output(transform = "pandas")

ct_inter.fit_transform(X_train)

      interaction__1  ...  interaction__Gr Liv Area TotRms AbvGrd
156              1.0  ...                                  3744.0
2560             1.0  ...                                  8512.0
299              1.0  ...                                  5955.0
961              1.0  ...                                 10262.0
1518             1.0  ...                                 11858.0
...              ...  ...                                     ...
1886             1.0  ...                                  4410.0
1921             1.0  ...                                  6336.0
1534             1.0  ...                                  8244.0
2899             1.0  ...                                 12600.0
1090             1.0  ...                                 17874.0

[2197 rows x 4 columns]

In [23]:
ct_dummies = ColumnTransformer(
  [("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"])],
  remainder = "passthrough"
).set_output(transform = "pandas")

ct_inter = ColumnTransformer(
  [
    ("interaction", PolynomialFeatures(interaction_only = True), ["remainder__TotRms AbvGrd", "dummify__Bldg Type_1Fam"]),
  ],
  remainder = "drop"
).set_output(transform = "pandas")

X_train_dummified = ct_dummies.fit_transform(X_train)
X_train_dummified

      dummify__Bldg Type_1Fam  ...  remainder__Sale Condition
156                       1.0  ...                     Normal
2560                      1.0  ...                     Normal
299                       0.0  ...                     Normal
961                       1.0  ...                     Normal
1518                      1.0  ...                     Normal
...                       ...  ...                        ...
1886                      1.0  ...                     Normal
1921                      1.0  ...                     Normal
1534                      1.0  ...                     Normal
2899                      1.0  ...                     Normal
1090                      1.0  ...                     Normal

[2197 rows x 85 columns]

In [24]:
ct_inter.fit_transform(X_train_dummified)

      interaction__1  ...  interaction__remainder__TotRms AbvGrd dummify__Bldg Type_1Fam
156              1.0  ...                                                4.0
2560             1.0  ...                                                7.0
299              1.0  ...                                                0.0
961              1.0  ...                                                7.0
1518             1.0  ...                                                7.0
...              ...  ...                                                ...
1886             1.0  ...                                                5.0
1921             1.0  ...                                                6.0
1534             1.0  ...                                                6.0
2899             1.0  ...                                                7.0
1090             1.0  ...                                                9.0

[2197 rows x 4 columns]

## Practice Activity

In [25]:
# Using only the size and number of rooms.

X = ames[["Gr Liv Area", "TotRms AbvGrd"]]
y = ames["SalePrice"]

lr_pipeline = Pipeline(
  [("linear_regression", LinearRegression())]
)

'''
lr_pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_pipeline_fitted = lr_pipeline.fit(X_train,y_train)

y_pred = lr_pipeline_fitted.predict(X_test)

mean_squared_error(y_test, y_pred)
'''

scores = cross_val_score(lr_pipeline, X, y, cv=5, scoring='neg_root_mean_squared_error')
print(abs(scores.mean()))

NameError: name 'cross_val_score' is not defined

In [ ]:
# Using size, number of rooms, and building type.

X = ames[["Gr Liv Area", "TotRms AbvGrd", "Bldg Type"]]
y = ames["SalePrice"]

ct = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
)

lr_pipeline2 = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
)

'''
lr_pipeline

X_train, X_test, y_train, y_test = train_test_split(X, y)

lr_pipeline_fitted = lr_pipeline.fit(X_train,y_train)

y_pred = lr_pipeline_fitted.predict(X_test)

mean_squared_error(y_test, y_pred)
'''

scores = cross_val_score(lr_pipeline2, X, y, cv=5, scoring='neg_root_mean_squared_error')
print(abs(scores.mean()))

In [26]:
# Using size and building type, and their interaction

X = ames[["Gr Liv Area", "Bldg Type"]]
y = ames["SalePrice"]

ct_dummies = ColumnTransformer(
  [("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
  ("standardize", StandardScaler(), ["Gr Liv Area"])], 
  remainder = "drop"
).set_output(transform = "pandas")

ct_inter = ColumnTransformer(
  [
    ("interaction1", PolynomialFeatures(interaction_only = True), ["standardize__Gr Liv Area", "dummify__Bldg Type_1Fam"]), 
    ("interaction2", PolynomialFeatures(interaction_only = True), ["standardize__Gr Liv Area", "dummify__Bldg Type_2fmCon"]),
    ("interaction3", PolynomialFeatures(interaction_only = True), ["standardize__Gr Liv Area", "dummify__Bldg Type_Duplex"]),
    ("interaction4", PolynomialFeatures(interaction_only = True), ["standardize__Gr Liv Area", "dummify__Bldg Type_Twnhs"]),
    ("interaction5", PolynomialFeatures(interaction_only = True), ["standardize__Gr Liv Area", "dummify__Bldg Type_TwnhsE"])
  ],
  remainder = "passthrough"
).set_output(transform = "pandas")

lr_pipeline3 = Pipeline(
  [("preprocessing", ct_dummies),
  ("interaction", ct_inter),
  ("linear_regression", LinearRegression())]
)

scores = cross_val_score(lr_pipeline3, X, y, cv=5, scoring='neg_root_mean_squared_error')
print(abs(scores.mean()))

NameError: name 'cross_val_score' is not defined

In [ ]:
# Using a 5-degree polynomial on size, a 5-degree polynomial on number of rooms, and also building type

X = ames[["Gr Liv Area", "Bldg Type", "TotRms AbvGrd"]]
y = ames["SalePrice"]

ct_dummies = ColumnTransformer(
  [("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
  ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])], 
  remainder = "drop"
).set_output(transform = "pandas")

ct_poly = ColumnTransformer(
  [
    ("poly1", PolynomialFeatures(degree = 5, interaction_only = False), ["standardize__Gr Liv Area"]), 
    ("poly2", PolynomialFeatures(degree = 5, interaction_only = False), ["standardize__TotRms AbvGrd"])
  ],
  remainder = "passthrough"
).set_output(transform = "pandas")

lr_pipeline4 = Pipeline(
  [("preprocessing", ct_dummies),
  ("preprocessing2", ct_poly),
  ("linear_regression", LinearRegression())]
)

scores = cross_val_score(lr_pipeline4, X, y, cv=5, scoring='neg_root_mean_squared_error')
print(abs(scores.mean()))

# Cross-Validating

In [ ]:
from sklearn.model_selection import cross_val_score

X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]


ct = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("standardize", StandardScaler(), ["Gr Liv Area", "TotRms AbvGrd"])
  ],
  remainder = "drop"
)

lr_pipeline_1 = Pipeline(
  [("preprocessing", ct),
  ("linear_regression", LinearRegression())]
).set_output(transform="pandas")


scores = cross_val_score(lr_pipeline_1, X, y, cv=5, scoring='r2')
scores

In [28]:
scores.mean()

NameError: name 'scores' is not defined

Cross validated r-squared is 0.53311

## Tuning

In [59]:
from sklearn.model_selection import GridSearchCV

X = ames.drop("SalePrice", axis = 1)
y = ames["SalePrice"]

ct_poly = ColumnTransformer(
  [
    ("dummify", OneHotEncoder(sparse_output = False), ["Bldg Type"]),
    ("polynomial", PolynomialFeatures(), ["Gr Liv Area"])
  ],
  remainder = "drop"
)

lr_pipeline_poly = Pipeline(
  [("preprocessing", ct_poly),
  ("linear_regression", LinearRegression())]
).set_output(transform="pandas")

degrees = {'preprocessing__polynomial__degree': np.arange(1, 10)}

gscv = GridSearchCV(lr_pipeline_poly, degrees, cv = 5, scoring='r2')

In [29]:
gscv_fitted = gscv.fit(X, y)

gscv_fitted.cv_results_

NameError: name 'gscv' is not defined

In [ ]:
gscv_fitted.cv_results_['mean_test_score']

In [30]:
pd.DataFrame(data = {"degrees": np.arange(1, 10), "scores": gscv_fitted.cv_results_['mean_test_score']})

NameError: name 'gscv_fitted' is not defined

In [62]:
# Consider one hundred modeling options for house price: 
# - House size, trying degrees 1 through 10
# - Number of rooms, trying degrees 1 through 10
# - Building Type

X = ames.drop("SalePrice", axis=1)
y = ames["SalePrice"]

# Define the ColumnTransformer with PolynomialFeatures and OneHotEncoder
ct_poly = ColumnTransformer(
    transformers=[
        ("dummify", OneHotEncoder(sparse_output=False), ["Bldg Type"]),
        ("polynomial1", PolynomialFeatures(), ["Gr Liv Area"]),
        ("polynomial2", PolynomialFeatures(), ["TotRms AbvGrd"])
    ],
    remainder="drop"
)

lr_pipeline_poly = Pipeline([
    ("preprocessing", ct_poly),
    ("linear_regression", LinearRegression())
]).set_output(transform="pandas")

param_grid = {
    'preprocessing__polynomial1__degree': np.arange(1, 11),
    'preprocessing__polynomial2__degree': np.arange(1, 11)
}

# Set up GridSearchCV with the updated param_grid
gscv = GridSearchCV(lr_pipeline_poly, param_grid, cv=5, scoring='r2')

In [31]:
gscv_fitted = gscv.fit(X, y)

gscv_fitted.cv_results_

NameError: name 'gscv' is not defined

In [ ]:
gscv_fitted.cv_results_['mean_test_score']

In [32]:
degrees = pd.DataFrame(gscv_fitted.cv_results_["params"])
results = degrees.assign(scores=gscv_fitted.cv_results_['mean_test_score'])
results.sort_values(by='scores', ascending=False)

NameError: name 'gscv_fitted' is not defined

GrLivArea with degree = 3 and TotRmsAbvGrd with degree = 1 has the highest R-squared